In [1]:
import sklearn

In [2]:
sklearn.__version__

'0.24.2'

In [4]:
# label = 정답(y값)
# X(feature:독립변수) / y(label:종속변수)
# 독립변수 끼리는 독립적(상관성이 높으면 안된다.) -> 높을 경우 다중공선성 문제 발생(예측에 크게 문제가 되지는 않는대..) / 종속변수는 독립변수와 상관성이 높아야 함.(그래야 예측이 잘 됨)
# 지도학습 : label로 모델 학습

In [3]:
# 붓꽃 품종 구분(Setoda, Vesicolor, Virginica) - 분류 dataset

In [5]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier    # 의사결정나무(이거 하나만으로는 예측에 부족하다.) / Classifier:분류  //  Regressor:회귀
from sklearn.model_selection import train_test_split    # 데이터 분리 모듈

import pandas as pd

In [6]:
# import 부분은 분리해서 실행시켜두고 작업해야 원활
iris = load_iris()

In [7]:
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [8]:
type(iris)

sklearn.utils.Bunch

In [9]:
# bunch? 딕셔너리처럼 이용가능?
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [10]:
iris['data']    # 'feature_names'의 각 요소에 해당하는 값

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [14]:
iris['feature_names']

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [13]:
iris['target']    # target_names의 인덱스값

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [12]:
iris['target_names']

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [15]:
iris_df = pd.DataFrame(data=iris.data,columns=iris.feature_names)
iris_df.head(2)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2

In [16]:
iris_df['label']=iris.target

In [17]:
iris_df.sample(2)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
85                 6.0               3.4                4.5               1.6   
125                7.2               3.2                6.0               1.8   

     label  
85       1  
125      2

In [23]:
# 전처리 후 학습
X_train,X_test,y_train,y_test = train_test_split(iris.data,
                                                 iris.target,
                                                 test_size=0.2,    # ,기준으로 줄바꿈이 가능하다.(\도 가능)
                                                 random_state=11)    # 논문같은 것 쓰려면 일정하게 랜덤해야 해서 사용.(몬말인지 알?)

In [19]:
X_train.shape,X_test.shape

((120, 4), (30, 4))

In [22]:
y_test    # shuffle이 기본 true로 설정 되어있음(iris.target은 sorting되어있음)

array([2, 2, 2, 1, 2, 0, 1, 0, 0, 1, 2, 1, 1, 2, 2, 0, 2, 1, 2, 2, 1, 0,
       0, 1, 0, 0, 2, 1, 0, 1])

In [24]:
# 1. 데이터 수집
# 2. 데이터 전처리
# 3. 학습?

In [26]:
# 머신러닝 = 스스로 가중치와 바이어스를 찾음.
# 의사결정나무는 어떻게 분류할 것인지 스스로 찾음

# 스스로 못찾는 경우 직접 세팅해줘야한다. : 하이퍼 파라메타**  -> 어떻게 넣느냐에 따라 성능이 확 달라진다.

In [27]:
dt_clf = DecisionTreeClassifier(random_state=11)    # 괄호 안에 shift+Tap하면 '하이퍼 파라메타' 확인 가능

In [28]:
dt_clf.fit(X_train,y_train)    # 지도학습이므로 target값도 넣어준다.

DecisionTreeClassifier(random_state=11)

In [29]:
pred = dt_clf.predict(X_test)

In [30]:
from sklearn.metrics import accuracy_score     # 평가와 관련된 것은 sklearn.metrics에 있다.    # accuracy_score : 정확도

In [31]:
accuracy_score(y_test,pred)    # 답과 예측값 비교

0.9333333333333333

In [32]:
# sklearn에서는 어떤 모델이던 fit(),predict()로 간단히 학습하고 예측결과를 반환한다.

In [33]:
# 교차검증 : 데이터를 여러등분해서 검증데이터를 바꿔가면서 테스트 후 종합

# cross_val_score()
# GridSearchCV

In [36]:
# 파이썬 머신러닝 완벽가이드 94-95p    : sklearn 모듈들 설명

In [35]:
# dataset.load_* 은 모듈처럼 불러올 수 있는데
# dataset.fetch_*은 용량이 커서 인터넷으로 다운 필요

In [39]:
# 데이터 분리 없이 100% 학습
iris = load_iris()
dt_clf = DecisionTreeClassifier()
train_data = iris.data
train_label = iris.target
dt_clf.fit(train_data,train_label)    # 학습

DecisionTreeClassifier()

In [40]:
pred = dt_clf.predict(train_data)

In [43]:
accuracy_score(train_label,pred)    # 학습한 데이터로 검증하면 의미없다. 새로운 데이터로 검증해야 얼마나 잘 예측하는지 알 수 있지.

1.0

In [44]:
# 과적합(overfitting) : 너무 세밀하게 학습. 내가 가진 데이터에만 너무 적합함. 조금 다른 문제를 전혀다른 문제라고 인식하게 되는 문제 발생. 다른 데이터로 수행하면 예측성능이 과도하게 떨어짐
# 과소적합(underfitting) : 공부를 덜 한 상태

In [45]:
# 교차검증

# K폴드 교차 검증 : (가장 보편적인 교차검증 기법) k개의 데이터폴드 세트를 만들어서 학습과 검증평가를 반복하는 방법
# KFold / StratifiedKFold    두가지 있음

# 마크다운 활용 https://bskyvision.com/1140

## K폴드

![](kfold.png)

In [47]:
from sklearn.model_selection import KFold
import numpy as np

In [60]:
iris = load_iris()
dt_clf = DecisionTreeClassifier(random_state=156)

kfold = KFold(n_splits=5, shuffle=True)    # n_split 기본 5개로 지정되어있음(그럼에도 적어주는 이유: 소스코드만 보고 이해하려고.) // shuffle안주니까 순서대로 분리해서 정확도 떨어졌대
cv_accuracy = []

n_iter = 0    # 몇 번 반복했는지 체크하려고
for train_index,test_index in kfold.split(iris.data):
    # print(train_index,test_index)
    X_train,X_test = iris.data[train_index],iris.data[test_index]    # data 분리
    y_train,y_test = iris.target[train_index],iris.target[test_index]    # label도 분리
    dt_clf.fit(X_train,y_train)
    pred = dt_clf.predict(X_test)
    n_iter += 1
    accuracy = np.round(accuracy_score(y_test,pred),4)    # 정확도 소수이하 4자리
    train_size = X_train.shape[0]
    test_size = X_test.shape[0]    # 몇 건인지?
    print(f'\n{n_iter} 교차검증정확도 : {accuracy}, 학습데이터크기 : {train_size}, 검증데이터크기 : {test_size}')
    print(f'{n_iter} 검증데이터 인덱스 : {test_index}')
    cv_accuracy.append(accuracy)    # 나중에 평균정확도 계산하려고,.

In [55]:
X_train,X_test    # 분리된 것 확인

(array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
        [5

In [62]:
np.mean(cv_accuracy)

0.94002

In [61]:
# stratified K 폴드    : 불균형한 분포도를 가진 레이블 집합을 위한 K폴드 방식
# ex) 대출사기 -> 소수의 경우일 것

In [63]:
iris_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     label  
0        0  
1        0  
2        0  
3        0  
4        0  
..     ...  
145      2  
146      2  
147      2  
148      2  
149      2  

[150 rows x 5 columns]

In [64]:
iris_df['label'].value_counts()

0    50
1    50
2    50
Name: label, dtype: int64

In [65]:
from sklearn.model_selection import StratifiedKFold

In [69]:
skf = StratifiedKFold(n_splits=3)
n_iter = 0
for train_index,test_index in skf.split(iris_df,iris_df['label']):
    n_iter+=1
    label_train = iris_df['label'].iloc[train_index]
    label_test = iris_df['label'].iloc[test_index]
    print(n_iter)
    print('학습\n',label_train.value_counts())
    print('검증\n',label_test.value_counts())
    print('-'*20)

1
학습
 2    34
0    33
1    33
Name: label, dtype: int64
검증
 0    17
1    17
2    16
Name: label, dtype: int64
--------------------
2
학습
 1    34
0    33
2    33
Name: label, dtype: int64
검증
 0    17
2    17
1    16
Name: label, dtype: int64
--------------------
3
학습
 0    34
1    33
2    33
Name: label, dtype: int64
검증
 1    17
2    17
0    16
Name: label, dtype: int64
--------------------


In [70]:
iris = load_iris()
dt_clf = DecisionTreeClassifier(random_state=156)

skfold = StratifiedKFold(n_splits=5, shuffle=True)    # n_split 기본 5개로 지정되어있음(그럼에도 적어주는 이유: 소스코드만 보고 이해하려고.) // shuffle안주니까 순서대로 분리해서 정확도 떨어졌대
cv_accuracy = []

n_iter = 0    # 몇 번 반복했는지 체크하려고
for train_index,test_index in kfold.split(iris.data):
    # print(train_index,test_index)
    X_train,X_test = iris.data[train_index],iris.data[test_index]    # data 분리
    y_train,y_test = iris.target[train_index],iris.target[test_index]    # label도 분리
    dt_clf.fit(X_train,y_train)
    pred = dt_clf.predict(X_test)
    n_iter += 1
    accuracy = np.round(accuracy_score(y_test,pred),4)    # 정확도 소수이하 4자리
    train_size = X_train.shape[0]
    test_size = X_test.shape[0]    # 몇 건인지?
    print(f'\n{n_iter} 교차검증정확도 : {accuracy}, 학습데이터크기 : {train_size}, 검증데이터크기 : {test_size}')
    print(f'{n_iter} 검증데이터 인덱스 : {test_index}')
    cv_accuracy.append(accuracy)    # 나중에 평균정확도 계산하려고,.


1 교차검증정확도 : 0.9, 학습데이터크기 : 120, 검증데이터크기 : 30
1 검증데이터 인덱스 : [  2   5   7  10  20  24  25  29  38  39  46  56  58  59  61  68  70  80
  81  94  98 106 108 110 123 133 139 142 145 148]

2 교차검증정확도 : 0.9667, 학습데이터크기 : 120, 검증데이터크기 : 30
2 검증데이터 인덱스 : [  3   4  17  22  30  33  35  36  37  40  45  47  50  71  74  77  79  87
  88  89  90  92 103 105 107 122 125 138 140 143]

3 교차검증정확도 : 1.0, 학습데이터크기 : 120, 검증데이터크기 : 30
3 검증데이터 인덱스 : [  6   9  11  12  16  18  26  27  31  48  52  55  60  64  66  73  75  76
  78  85  93  97 114 115 116 117 126 131 147 149]

4 교차검증정확도 : 0.9667, 학습데이터크기 : 120, 검증데이터크기 : 30
4 검증데이터 인덱스 : [ 13  14  19  21  32  34  41  42  51  53  63  67  69  72  84  95  99 100
 101 104 111 118 121 124 127 129 132 134 141 146]

5 교차검증정확도 : 0.9, 학습데이터크기 : 120, 검증데이터크기 : 30
5 검증데이터 인덱스 : [  0   1   8  15  23  28  43  44  49  54  57  62  65  82  83  86  91  96
 102 109 112 113 119 120 128 130 135 136 137 144]


In [71]:
# 20220411    12시 영상 앞부분 컨닝 = 윗셀

In [72]:
from sklearn.model_selection import cross_val_score

In [73]:
iris = load_iris()
dt_clf = DecisionTreeClassifier(random_state=156)

In [75]:
cross_val_score(dt_clf,iris.data,iris.target,scoring='accuracy',cv=3)    # 정확도만 보기

array([0.98, 0.94, 0.98])

In [89]:
# GridSearchCV : 교차검증과 하이퍼 파라미터 튜닝을 한번에 함    -- 튜닝해가면서 정확도 계산 가능  <-- 그래서 cross_val_score 보다 많이 쓰임
grid_parameters = { 'max_depth':[1,2,3],
                    'min_samples_split':[2,3]}

In [78]:
iris = load_iris()
X_train,X_test,y_train,y_test = train_test_split(iris.data,
                                                 iris.target,
                                                 test_size=0.2,
                                                 random_state=121)
dt_clf = DecisionTreeClassifier()

In [79]:
# import pandas as pd
from sklearn.model_selection import GridSearchCV

In [80]:
grid_dtree = GridSearchCV(dt_clf,param_grid=grid_parameters,cv=3,refit=True)

In [81]:
grid_dtree.fit(X_train,y_train)

GridSearchCV(cv=3, estimator=DecisionTreeClassifier(),
             param_grid={'max_depth': [1, 2, 3], 'min_samples_split': [2, 3]})

In [83]:
grid_dtree.cv_results_    # 결괏값 - 보기 불편하긴 해..

{'mean_fit_time': array([0.00066487, 0.        , 0.00033236, 0.00033228, 0.00033236,
        0.00033275]),
 'std_fit_time': array([0.00047013, 0.        , 0.00047002, 0.00046991, 0.00047002,
        0.00047058]),
 'mean_score_time': array([0.00033259, 0.        , 0.        , 0.        , 0.        ,
        0.        ]),
 'std_score_time': array([0.00047036, 0.        , 0.        , 0.        , 0.        ,
        0.        ]),
 'param_max_depth': masked_array(data=[1, 1, 2, 2, 3, 3],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_min_samples_split': masked_array(data=[2, 3, 2, 3, 2, 3],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'max_depth': 1, 'min_samples_split': 2},
  {'max_depth': 1, 'min_samples_split': 3},
  {'max_depth': 2, 'min_samples_split': 2},
  {'max_depth': 2, 'min_samples_split': 3},
  {'max_depth': 3, 'min_sample

In [84]:
grid_dtree.best_params_

{'max_depth': 3, 'min_samples_split': 2}

In [85]:
scoreds_df = pd.DataFrame(grid_dtree.cv_results_)
scoreds_df

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0       0.000665      0.000470         0.000333         0.00047   
1       0.000000      0.000000         0.000000         0.00000   
2       0.000332      0.000470         0.000000         0.00000   
3       0.000332      0.000470         0.000000         0.00000   
4       0.000332      0.000470         0.000000         0.00000   
5       0.000333      0.000471         0.000000         0.00000   

  param_max_depth param_min_samples_split  \
0               1                       2   
1               1                       3   
2               2                       2   
3               2                       3   
4               3                       2   
5               3                       3   

                                     params  split0_test_score  \
0  {'max_depth': 1, 'min_samples_split': 2}              0.700   
1  {'max_depth': 1, 'min_samples_split': 3}              0.700   
2  {'max_depth': 2, 'min_samples_split': 2}              0.925   
3  {'max_depth': 2, 'min_samples_split': 3}              0.925   
4  {'max_depth': 3, 'min_samples_split': 2}              0.975   
5  {'max_depth': 3, 'min_samples_split': 3}              0.975   

   split1_test_score  split2_test_score  mean_test_score  std_test_score  \
0                0.7               0.70         0.700000    1.110223e-16   
1                0.7               0.70         0.700000    1.110223e-16   
2                1.0               0.95         0.958333    3.118048e-02   
3                1.0               0.95         0.958333    3.118048e-02   
4                1.0               0.95         0.975000    2.041241e-02   
5                1.0               0.95         0.975000    2.041241e-02   

   rank_test_score  
0                5  
1                5  
2                3  
3                3  
4                1  
5                1

In [86]:
scoreds_df.columns

Index(['mean_fit_time', 'std_fit_time', 'mean_score_time', 'std_score_time',
       'param_max_depth', 'param_min_samples_split', 'params',
       'split0_test_score', 'split1_test_score', 'split2_test_score',
       'mean_test_score', 'std_test_score', 'rank_test_score'],
      dtype='object')

In [87]:
scoreds_df[['params','mean_test_score', 'rank_test_score','split0_test_score', 'split1_test_score', 'split2_test_score']]    # 파라미터,평균값,순위,1~3번째 점수들

params  mean_test_score  rank_test_score  \
0  {'max_depth': 1, 'min_samples_split': 2}         0.700000                5   
1  {'max_depth': 1, 'min_samples_split': 3}         0.700000                5   
2  {'max_depth': 2, 'min_samples_split': 2}         0.958333                3   
3  {'max_depth': 2, 'min_samples_split': 3}         0.958333                3   
4  {'max_depth': 3, 'min_samples_split': 2}         0.975000                1   
5  {'max_depth': 3, 'min_samples_split': 3}         0.975000                1   

   split0_test_score  split1_test_score  split2_test_score  
0              0.700                0.7               0.70  
1              0.700                0.7               0.70  
2              0.925                1.0               0.95  
3              0.925                1.0               0.95  
4              0.975                1.0               0.95  
5              0.975                1.0               0.95

In [90]:
# Garbage in / Garbage out

In [91]:
# 문자열 -> 숫자

# 레이블 인코딩

In [92]:
from sklearn.preprocessing import LabelEncoder    #전처리 - 레이블 인코더 : 정수형태로 바꿔준다.

In [99]:
items = ['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']    # 리스트형태 -> ndarray형태로 처리 가능
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
labels    # 목록의 인덱스값을 찾아줌

array([0, 1, 4, 5, 3, 3, 2, 2])

In [97]:
encoder.classes_    # 만들어진 사전 확인

array(['TV', '냉장고', '믹서', '선풍기', '전자레인지', '컴퓨터'], dtype='<U5')

In [100]:
encoder.inverse_transform([0,2,4,5])

array(['TV', '믹서', '전자레인지', '컴퓨터'], dtype='<U5')

In [101]:
# 숫자가 클수록 영향력을 크게 주기 가능
# 딥러닝은 숫자 영향 받음 -> 레이블 인코딩한 자료를 쓰면 문제 발생할 수 있다.
# 머신러닝은 회귀 시에 숫자의 크고 작음의 영향이 없을 수도 있다. 

In [102]:
# 그래서 나온 것이 '원-핫 인코딩' 나머지는 '0' 하나만 '1'

In [103]:
from sklearn.preprocessing import OneHotEncoder

In [104]:
items

['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']

In [107]:
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.fit_transform(items)
labels = labels.reshape(-1,1)    # (-1,1)모르겠어어ㅓㅓㅓ**

In [109]:
oh_encoder = OneHotEncoder()
oh_labels = oh_encoder.fit_transform(labels)

In [110]:
oh_labels

<8x6 sparse matrix of type '<class 'numpy.float64'>'
	with 8 stored elements in Compressed Sparse Row format>

In [111]:
oh_labels.toarray()

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.]])

In [113]:
oh_labels.shape

(8, 6)

In [114]:
# 숫자로 바꾸는 두가지 방법 - LabelEncoder, OneHotEncoder

In [115]:
df = pd.DataFrame({'item':['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']})

In [116]:
df

item
0     TV
1    냉장고
2  전자레인지
3    컴퓨터
4    선풍기
5    선풍기
6     믹서
7     믹서

In [117]:
pd.get_dummies(df)

item_TV  item_냉장고  item_믹서  item_선풍기  item_전자레인지  item_컴퓨터
0        1         0        0         0           0         0
1        0         1        0         0           0         0
2        0         0        0         0           1         0
3        0         0        0         0           0         1
4        0         0        0         1           0         0
5        0         0        0         1           0         0
6        0         0        1         0           0         0
7        0         0        1         0           0         0

In [118]:
# 피처 스케일링 (표준화 / 정규화)
# 표준화 : 평균이 0이고,분산이 1인 가우시안 분포를 가진 값으로 변환  <-- 데이터가 정규분포를 띠면 표준화 작업을 한다.
# 정규화 : 최소 0~ 최대 1을 가지는 값으로 변환  <-- 데이터가 ?면 정규화 작업을 한다.(못들어따..**) 서로 다른 피처 크기 통일하기 위함

# 키는 표준화?정규화? -> 표준화
# 정규화 예시는요??** 몰라옇ㅎ

In [121]:
iris = load_iris()
iris_df = pd.DataFrame(data=iris.data,columns=iris.feature_names)    # 윗줄 실행 안된 상태라 Tap키 안먹음

In [122]:
iris_df.mean()

sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64

In [123]:
iris_df.var()

sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64

In [124]:
from sklearn.preprocessing import StandardScaler

In [133]:
scaler = StandardScaler()    # 표준화?? 평균이 0, 분산이 1

In [127]:
iris_scaled = scaler.fit_transform(iris_df)

In [128]:
iris_scaled

array([[-9.00681170e-01,  1.01900435e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00, -1.31979479e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.38535265e+00,  3.28414053e-01, -1.39706395e+00,
        -1.31544430e+00],
       [-1.50652052e+00,  9.82172869e-02, -1.28338910e+00,
        -1.31544430e+00],
       [-1.02184904e+00,  1.24920112e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-5.37177559e-01,  1.93979142e+00, -1.16971425e+00,
        -1.05217993e+00],
       [-1.50652052e+00,  7.88807586e-01, -1.34022653e+00,
        -1.18381211e+00],
       [-1.02184904e+00,  7.88807586e-01, -1.28338910e+00,
        -1.31544430e+00],
       [-1.74885626e+00, -3.62176246e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00,  9.82172869e-02, -1.28338910e+00,
        -1.44707648e+00],
       [-5.37177559e-01,  1.47939788e+00, -1.28338910e+00,
        -1.31544430e+00],
       [-1.26418478e+00,  7.88807586e-01, -1.22655167e+00,
      

In [130]:
iris_df_scaled = pd.DataFrame(data=iris_scaled,columns=iris.feature_names)

In [131]:
iris_df_scaled.mean()

sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64

In [132]:
iris_df_scaled.var()

sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64

In [134]:
# MinMaxScaler <-- 데이터의 분포가 정규분포(가우시안 분포)형태가 아닌 경우
from sklearn.preprocessing import MinMaxScaler

In [135]:
scaler = MinMaxScaler()

In [136]:
iris_scale = scaler.fit_transform(iris_df)

In [137]:
iris_df_scaled = pd.DataFrame(data=iris_scaled,columns=iris.feature_names)

In [138]:
iris_df.min(),iris_df.max()

(sepal length (cm)    4.3
 sepal width (cm)     2.0
 petal length (cm)    1.0
 petal width (cm)     0.1
 dtype: float64,
 sepal length (cm)    7.9
 sepal width (cm)     4.4
 petal length (cm)    6.9
 petal width (cm)     2.5
 dtype: float64)

In [140]:
iris_df_scaled.min(),iris_df_scaled.max()    # min:0, max:1 나와야하는디요??? **

(sepal length (cm)   -1.870024
 sepal width (cm)    -2.433947
 petal length (cm)   -1.567576
 petal width (cm)    -1.447076
 dtype: float64,
 sepal length (cm)    2.492019
 sepal width (cm)     3.090775
 petal length (cm)    1.785832
 petal width (cm)     1.712096
 dtype: float64)

In [141]:
# fit(학습할 전체 데이터)
# transform(전체, 부분 데이터 가능)
# fit_transform 사용시 주의

In [145]:
train_array = np.arange(11).reshape(-1,1)    # (-1,1) : 행은 알아서 열은 하나씩 이라는 뜻이래'
test_array = np.arange(6).reshape(-1,1)

In [143]:
train_array

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [146]:
test_array

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [147]:
scaler = MinMaxScaler()

In [148]:
scaler.fit(train_array)

MinMaxScaler()

In [149]:
scaler.transform(train_array)

array([[0. ],
       [0.1],
       [0.2],
       [0.3],
       [0.4],
       [0.5],
       [0.6],
       [0.7],
       [0.8],
       [0.9],
       [1. ]])

In [151]:
scaler.transform(test_array)    # 학습에 사용한 데이터를 기준으로 스케일링

array([[0. ],
       [0.1],
       [0.2],
       [0.3],
       [0.4],
       [0.5]])

In [153]:
scaler.fit(test_array)

MinMaxScaler()

In [154]:
scaler.transform(test_array)

array([[0. ],
       [0.2],
       [0.4],
       [0.6],
       [0.8],
       [1. ]])

In [156]:
scaler.transform(train_array)    # 일부 데이터(test_array)로 학습시켰기 때문에 정상적이지 않은 결과(1보다 큰 값)가 나왔다.

array([[0. ],
       [0.2],
       [0.4],
       [0.6],
       [0.8],
       [1. ],
       [1.2],
       [1.4],
       [1.6],
       [1.8],
       [2. ]])